// Textos del sitio en espanol e ingles. Sin guiones como puntuacion.
export const TEXTOS = {
  es: {
    doc: "La Odisea, en gran formato",
    marca: "La Odisea",
    idioma: "English",
    sonido: "Sonido",
    titulo: "La Odisea",
    invocacion: "Háblame, Musa, de aquel varón de multiforme ingenio que, después de destruir la sacra ciudad de Troya, anduvo peregrinando larguísimo tiempo.",
    fuente: "Homero, Odisea, canto I. Traducción de Luis Segalá, 1910.",
    zarpar: "Desliza para zarpar",
    premisaTitulo: "Diez años de guerra. Diez años para volver.",
    premisa: "La Odisea es el poema del regreso. Homero la cantó hace unos 2.700 años y sigue siendo el molde de casi todos los viajes que has visto en una pantalla. Esta guía recorre las catorce escalas de Odiseo, en orden, para que entres a la sala sabiendo lo que el público de Homero ya sabía.",
    premisaNota: "Sí, esto adelanta la trama del poema. No la de la película: Nolan cuenta su propia versión.",
    escalaDe: (n) => `Escala ${n} de XIV`,
    clave: "La clave",
    rollo: "Secuencia renderizada en Blender para esta guía",
    escalas: [
      { n: "I", lugar: "Troya", lema: "El fin de una guerra",
        relato: "Diez años de asedio terminan con un engaño: un caballo de madera con soldados escondidos en su vientre. La idea fue de Odiseo. Troya arde, y los griegos cometen excesos que ofenden a los dioses. Odiseo zarpa hacia Ítaca, su isla, con doce naves. Cree que el viaje durará semanas. Durará diez años.",
        clave: "Todo el poema es el precio de esa victoria. El hombre más astuto de Grecia pasa el resto de la historia pagándola." },
      { n: "II", lugar: "Los cícones", lema: "La codicia",
        relato: "Primera escala, primer error. Odiseo y sus hombres saquean la ciudad de Ísmaro y, en lugar de huir con el botín, se quedan bebiendo en la playa. Los cícones vuelven al amanecer con refuerzos. Mueren seis hombres de cada nave.",
        clave: "Odiseo manda, pero no controla a su tripulación. Esa tensión entre el líder y sus hombres atraviesa todo el viaje." },
      { n: "III", lugar: "Los lotófagos", lema: "El olvido",
        relato: "Una tormenta los arrastra nueve días hasta la tierra de los que comen loto. Nadie los ataca: les ofrecen una flor dulce que borra el deseo de volver a casa. Los que la prueban solo quieren quedarse. Odiseo los lleva a rastras, llorando, y los ata a los bancos de las naves.",
        clave: "El peligro más sutil del poema no es un monstruo. Es dejar de querer volver. Homero lo pone al principio a propósito." },
      { n: "IV", lugar: "Polifemo", lema: "Nadie",
        relato: "En la isla de los cíclopes entran a una cueva llena de quesos y corderos. El dueño es Polifemo, un gigante de un solo ojo, hijo de Poseidón. Los encierra con una roca y empieza a devorarlos, dos por comida. Odiseo le dice que se llama Nadie, lo emborracha y le clava una estaca ardiente en el ojo. Cuando los otros cíclopes preguntan quién lo ataca, Polifemo grita: «¡Nadie!».",
        clave: "Al huir, Odiseo no resiste y grita su nombre verdadero. Ese acto de orgullo le gana la furia de Poseidón. Es el error que define el viaje." },
      { n: "V", lugar: "Eolo", lema: "Tan cerca",
        relato: "El dios de los vientos le regala un odre de cuero con todos los vientos contrarios encerrados. Navegan nueve días en calma, hasta ver las fogatas de Ítaca. Odiseo, agotado, se duerme. Sus hombres, convencidos de que el odre esconde oro, lo abren. La tempestad los devuelve al punto de partida.",
        clave: "La escena más cruel del poema: ver la casa y perderla por desconfianza." },
      { n: "VI", lugar: "Los lestrigones", lema: "La masacre",
        relato: "Entran a un puerto rodeado de acantilados. Es una trampa: los lestrigones, gigantes caníbales, lanzan rocas desde lo alto y arponean a los marineros como si fueran peces. Once naves se hunden. Solo sobrevive la de Odiseo, que había quedado amarrada afuera.",
        clave: "En pocas líneas, Homero borra casi toda la flota. Desde aquí, Odiseo navega con un solo barco y una tripulación que ya no confía en él." },
      { n: "VII", lugar: "Circe", lema: "La hechicera",
        relato: "En la isla de Eea, la hechicera Circe convierte en cerdos a los hombres que Odiseo envió a explorar. El dios Hermes le da una hierba que lo protege del hechizo. Circe, vencida, devuelve a los hombres su forma, y Odiseo se queda con ella un año entero.",
        clave: "Nadie lo obliga a quedarse. Es uno de los pasajes más incómodos para leer al héroe: un año que no parece tener prisa." },
      { n: "VIII", lugar: "El inframundo", lema: "Los muertos",
        relato: "Solo el adivino Tiresias puede decirle cómo volver, y Tiresias está muerto. Odiseo navega hasta el borde del mundo, cava un foso, derrama sangre y las almas acuden a beber. Habla con Tiresias, con Aquiles y con su propia madre, que murió esperándolo. Tres veces intenta abrazarla. Tres veces se le escapa como una sombra.",
        clave: "Aquiles le confiesa que preferiría ser un esclavo vivo antes que rey de los muertos. La gloria, vista desde abajo, no vale nada." },
      { n: "IX", lugar: "Las sirenas", lema: "El canto",
        relato: "Las sirenas cantan una música que nadie puede escuchar sin lanzarse al mar. Los huesos de sus víctimas cubren su isla. Odiseo tapa con cera los oídos de sus hombres y se hace atar al mástil, porque él sí quiere oírlas. Les ordena que, si suplica que lo suelten, aprieten más las cuerdas.",
        clave: "Odiseo no evita la tentación: diseña la manera de sobrevivir a ella. Es la imagen más famosa del poema, y la más humana." },
      { n: "X", lugar: "Escila y Caribdis", lema: "El mal menor",
        relato: "Un estrecho con dos amenazas. De un lado, Caribdis, un remolino que traga el mar tres veces al día. Del otro, Escila, un monstruo de seis cabezas oculto en una cueva del acantilado. Odiseo elige pasar junto a Escila, sabiendo lo que costará. Seis hombres son arrancados de la cubierta.",
        clave: "No hay opción buena, solo una menos mala. Odiseo no se lo advierte a sus hombres. Observa cómo carga con esa decisión." },
      { n: "XI", lugar: "Las vacas del Sol", lema: "El sacrilegio",
        relato: "Varados en la isla de Helios, el dios Sol, y muertos de hambre, los hombres sacrifican las vacas sagradas mientras Odiseo duerme. Zeus responde con un rayo que parte la nave en dos. Todos mueren. Odiseo sobrevive solo, aferrado al mástil.",
        clave: "Tiresias se lo había advertido. La tripulación entera muere por su propia decisión, y Odiseo queda solo por primera vez." },
      { n: "XII", lugar: "Calipso", lema: "La jaula de oro",
        relato: "La ninfa Calipso lo retiene siete años en su isla y le ofrece la inmortalidad si se queda. Él pasa los días en la orilla, mirando el mar y llorando. Los dioses finalmente le ordenan dejarlo partir, y Odiseo construye una balsa con sus propias manos.",
        clave: "Rechaza ser un dios para volver a una vida mortal, junto a una esposa que envejece. Esa decisión es el corazón del poema." },
      { n: "XIII", lugar: "Los feacios", lema: "El relato",
        relato: "Náufrago y desnudo, llega a la isla de los feacios. La princesa Nausícaa lo encuentra y el rey lo recibe sin saber quién es. En el banquete, un poeta canta sobre Troya y Odiseo llora. Entonces revela su nombre y cuenta todo lo que acabas de leer. Los feacios lo llevan dormido a Ítaca en una sola noche.",
        clave: "Casi todo el viaje es un relato en primera persona, contado por un narrador que miente con talento. ¿Cuánto pasó exactamente así?" },
      { n: "XIV", lugar: "Ítaca", lema: "El arco",
        relato: "Veinte años después de partir, llega disfrazado de mendigo. Más de cien pretendientes ocupan su casa, devoran su hacienda y presionan a Penélope para que elija un nuevo esposo. Ella propone una prueba: tensar el arco de Odiseo y atravesar con una flecha doce hachas alineadas. Ninguno logra tensarlo. El mendigo sí. Después apunta a los pretendientes.",
        clave: "La venganza es total, y el poema no la suaviza. Luego Penélope pone a prueba al extraño con un secreto que solo su esposo conoce: la cama tallada en un olivo vivo." },
    ],
    personajesTitulo: "Quiénes mueven la historia",
    personajes: [
      { nombre: "Odiseo", rol: "Rey de Ítaca", texto: "El más astuto de los griegos, y también el más orgulloso. Miente con facilidad y llora a menudo.", actor: "En la película: Matt Damon" },
      { nombre: "Penélope", rol: "Reina de Ítaca", texto: "Veinte años resistiendo con ingenio: de día teje un sudario y de noche lo desteje para ganar tiempo.", actor: "En la película: Anne Hathaway" },
      { nombre: "Telémaco", rol: "Su hijo", texto: "Tenía meses cuando su padre partió. Los primeros cantos son suyos: un joven que sale a buscar a un desconocido.", actor: "En la película: Tom Holland" },
      { nombre: "Atenea", rol: "Diosa de la inteligencia", texto: "Protectora de Odiseo. Se disfraza, aconseja, manipula. Sin ella no hay regreso." },
      { nombre: "Poseidón", rol: "Dios del mar", texto: "Padre de Polifemo. Su rencor es el motor del viaje: cada tormenta es personal." },
      { nombre: "Polifemo", rol: "Cíclope", texto: "Pastor y caníbal. La maldición que lanza contra Odiseo se cumple palabra por palabra." },
      { nombre: "Circe", rol: "Hechicera de Eea", texto: "Primero enemiga, después aliada: es quien le indica el camino hacia los muertos." },
      { nombre: "Calipso", rol: "Ninfa", texto: "Lo ama y lo retiene siete años. Su oferta, la inmortalidad, es la tentación más grande del poema." },
    ],
    cantosTitulo: "Veinticuatro cantos. Casi nada de lo famoso.",
    cantos: [
      { de: 1, a: 4, texto: "Telémaco busca a su padre" },
      { de: 5, a: 8, texto: "De Calipso a los feacios" },
      { de: 9, a: 12, texto: "El relato del viaje" },
      { de: 13, a: 24, texto: "La venganza en Ítaca" },
    ],
    cantosNota: "Las aventuras que todos conocen ocupan solo cuatro cantos, y se cuentan como un recuerdo. La mitad del poema ocurre en Ítaca. Homero empezó la historia por el medio mucho antes que Nolan.",
    cantoAbrev: (a, b) => `Cantos ${a} a ${b}`,
    salaTitulo: "Antes de que se apaguen las luces",
    sala: [
      { t: "Elige la pantalla más grande.", d: "Nolan pensó esta película para IMAX. El mar, en una pantalla chica, pierde la mitad de su peso." },
      { t: "No esperes el orden de esta guía.", d: "El poema empieza por el medio y salta en el tiempo. La película puede hacer lo mismo, y ahora sabrás ubicarte." },
      { t: "Sigue a los dioses.", d: "Cada tormenta tiene un autor. Cuando algo sale mal en el mar, pregúntate quién está enojado y por qué." },
      { t: "Son 172 minutos.", d: "Llega temprano y con tiempo. Esta historia tardó veinte años en terminar; tres horas es poco." },
    ],
    hechoPor: "Hecho por",
    otraVersion: "¿Viajas con niños? Mira la versión ilustrada",
    otraVersionUrl: "../",
  },
  en: {
    doc: "The Odyssey, in large format",
    marca: "The Odyssey",
    idioma: "Español",
    sonido: "Sound",
    titulo: "The Odyssey",
    invocacion: "Tell me, O muse, of that ingenious hero who travelled far and wide after he had sacked the famous town of Troy.",
    fuente: "Homer, Odyssey, Book I. Translated by Samuel Butler, 1900.",
    zarpar: "Scroll to set sail",
    premisaTitulo: "Ten years of war. Ten years to get home.",
    premisa: "The Odyssey is the poem of the return. Homer sang it roughly 2,700 years ago, and it is still the blueprint for nearly every journey you have seen on a screen. This guide sails through Odysseus's fourteen stops, in order, so you walk into the theater knowing what Homer's audience already knew.",
    premisaNota: "Yes, this gives away the plot of the poem. Not the film's: Nolan tells his own version.",
    escalaDe: (n) => `Stop ${n} of XIV`,
    clave: "The key",
    rollo: "Sequence rendered in Blender for this guide",
    escalas: [
      { n: "I", lugar: "Troy", lema: "The end of a war",
        relato: "Ten years of siege end with a trick: a wooden horse with soldiers hidden in its belly. It was Odysseus's idea. Troy burns, and the Greeks commit atrocities that offend the gods. Odysseus sails for Ithaca, his island, with twelve ships. He thinks the journey will take weeks. It will take ten years.",
        clave: "The whole poem is the price of that victory. The cleverest man in Greece spends the rest of the story paying for it." },
      { n: "II", lugar: "The Cicones", lema: "Greed",
        relato: "First stop, first mistake. Odysseus and his men sack the city of Ismarus and, instead of fleeing with the plunder, stay on the beach drinking. The Cicones return at dawn with reinforcements. Six men die from every ship.",
        clave: "Odysseus commands, but he does not control his crew. That tension between the leader and his men runs through the whole voyage." },
      { n: "III", lugar: "The Lotus Eaters", lema: "Forgetting",
        relato: "A storm drives them nine days to the land of the Lotus Eaters. Nobody attacks them: they are offered a sweet flower that erases the desire to go home. Those who taste it only want to stay. Odysseus drags them back in tears and ties them to the benches of the ships.",
        clave: "The subtlest danger in the poem is not a monster. It is no longer wanting to go home. Homer puts it first on purpose." },
      { n: "IV", lugar: "Polyphemus", lema: "Nobody",
        relato: "On the island of the Cyclopes they enter a cave full of cheeses and lambs. The owner is Polyphemus, a giant with a single eye and a son of Poseidon. He seals them in with a boulder and starts devouring them, two per meal. Odysseus tells him his name is Nobody, gets him drunk and drives a burning stake into his eye. When the other Cyclopes ask who is attacking him, Polyphemus screams: \u201cNobody!\u201d",
        clave: "As he escapes, Odysseus cannot resist shouting his real name. That act of pride earns him Poseidon's fury. It is the mistake that defines the voyage." },
      { n: "V", lugar: "Aeolus", lema: "So close",
        relato: "The god of the winds gives him a leather bag holding every contrary wind. They sail nine days in calm, until they can see the fires of Ithaca. Exhausted, Odysseus falls asleep. His men, convinced the bag hides gold, open it. The storm blows them back to where they started.",
        clave: "The cruelest scene in the poem: seeing home and losing it to suspicion." },
      { n: "VI", lugar: "The Laestrygonians", lema: "The massacre",
        relato: "They enter a harbor ringed by cliffs. It is a trap: the Laestrygonians, cannibal giants, hurl boulders from above and spear the sailors like fish. Eleven ships go down. Only Odysseus's survives, moored outside.",
        clave: "In a few lines Homer wipes out almost the entire fleet. From here on, Odysseus sails with one ship and a crew that no longer trusts him." },
      { n: "VII", lugar: "Circe", lema: "The sorceress",
        relato: "On the island of Aeaea, the sorceress Circe turns the men Odysseus sent to scout into pigs. The god Hermes gives him an herb that protects him from her spell. Defeated, Circe restores the men, and Odysseus stays with her for a whole year.",
        clave: "Nobody forces him to stay. It is one of the most uncomfortable passages for reading the hero: a year that seems in no hurry at all." },
      { n: "VIII", lugar: "The Underworld", lema: "The dead",
        relato: "Only the prophet Tiresias can tell him how to get home, and Tiresias is dead. Odysseus sails to the edge of the world, digs a trench, pours out blood, and the souls come to drink. He speaks with Tiresias, with Achilles, and with his own mother, who died waiting for him. Three times he tries to embrace her. Three times she slips away like a shadow.",
        clave: "Achilles confesses he would rather be a living slave than king of the dead. Glory, seen from below, is worth nothing." },
      { n: "IX", lugar: "The Sirens", lema: "The song",
        relato: "The Sirens sing music no one can hear without throwing himself into the sea. The bones of their victims cover their island. Odysseus plugs his men's ears with wax and has himself tied to the mast, because he wants to hear them. He orders that if he begs to be released, they tighten the ropes.",
        clave: "Odysseus does not avoid temptation: he designs a way to survive it. It is the most famous image in the poem, and the most human." },
      { n: "X", lugar: "Scylla and Charybdis", lema: "The lesser evil",
        relato: "A strait with two threats. On one side, Charybdis, a whirlpool that swallows the sea three times a day. On the other, Scylla, a monster with six heads hidden in a cliffside cave. Odysseus chooses to pass by Scylla, knowing what it will cost. Six men are snatched from the deck.",
        clave: "There is no good option, only a less bad one. Odysseus does not warn his men. Watch how he carries that decision." },
      { n: "XI", lugar: "The cattle of the Sun", lema: "Sacrilege",
        relato: "Stranded on the island of Helios, the Sun god, and starving, the men slaughter his sacred cattle while Odysseus sleeps. Zeus answers with a thunderbolt that splits the ship in two. Everyone dies. Odysseus survives alone, clinging to the mast.",
        clave: "Tiresias had warned them. The entire crew dies by its own decision, and Odysseus is alone for the first time." },
      { n: "XII", lugar: "Calypso", lema: "The golden cage",
        relato: "The nymph Calypso keeps him on her island for seven years and offers him immortality if he stays. He spends his days on the shore, staring at the sea and weeping. The gods finally order her to let him go, and Odysseus builds a raft with his own hands.",
        clave: "He turns down becoming a god to return to a mortal life, beside a wife who is growing old. That decision is the heart of the poem." },
      { n: "XIII", lugar: "The Phaeacians", lema: "The tale",
        relato: "Shipwrecked and naked, he reaches the island of the Phaeacians. Princess Nausicaa finds him and the king takes him in without knowing who he is. At the banquet a poet sings of Troy and Odysseus weeps. Then he reveals his name and tells everything you have just read. The Phaeacians carry him, asleep, to Ithaca in a single night.",
        clave: "Most of the voyage is a first person account, told by a narrator who lies brilliantly. How much of it happened exactly like this?" },
      { n: "XIV", lugar: "Ithaca", lema: "The bow",
        relato: "Twenty years after leaving, he arrives disguised as a beggar. More than a hundred suitors occupy his house, devour his estate and pressure Penelope to choose a new husband. She proposes a test: string Odysseus's bow and shoot an arrow through twelve axes set in a row. None of them can string it. The beggar can. Then he takes aim at the suitors.",
        clave: "The revenge is total, and the poem does not soften it. Afterwards Penelope tests the stranger with a secret only her husband knows: the bed carved from a living olive tree." },
    ],
    personajesTitulo: "Who drives the story",
    personajes: [
      { nombre: "Odysseus", rol: "King of Ithaca", texto: "The cleverest of the Greeks, and also the proudest. He lies easily and weeps often.", actor: "In the film: Matt Damon" },
      { nombre: "Penelope", rol: "Queen of Ithaca", texto: "Twenty years of holding out with wit: she weaves a shroud by day and unravels it by night to buy time.", actor: "In the film: Anne Hathaway" },
      { nombre: "Telemachus", rol: "His son", texto: "He was a baby when his father left. The first books are his: a young man setting out to find a stranger.", actor: "In the film: Tom Holland" },
      { nombre: "Athena", rol: "Goddess of wisdom", texto: "Odysseus's protector. She disguises herself, advises, manipulates. Without her there is no homecoming." },
      { nombre: "Poseidon", rol: "God of the sea", texto: "Father of Polyphemus. His grudge drives the voyage: every storm is personal." },
      { nombre: "Polyphemus", rol: "Cyclops", texto: "Shepherd and cannibal. The curse he lays on Odysseus comes true word for word." },
      { nombre: "Circe", rol: "Sorceress of Aeaea", texto: "First an enemy, then an ally: she is the one who shows him the way to the dead." },
      { nombre: "Calypso", rol: "Nymph", texto: "She loves him and keeps him for seven years. Her offer, immortality, is the greatest temptation in the poem." },
    ],
    cantosTitulo: "Twenty four books. Almost none of the famous parts.",
    cantos: [
      { de: 1, a: 4, texto: "Telemachus searches for his father" },
      { de: 5, a: 8, texto: "From Calypso to the Phaeacians" },
      { de: 9, a: 12, texto: "The tale of the voyage" },
      { de: 13, a: 24, texto: "The revenge on Ithaca" },
    ],
    cantosNota: "The adventures everyone knows take up only four books, and they are told as a memory. Half the poem happens on Ithaca. Homer started his story in the middle long before Nolan did.",
    cantoAbrev: (a, b) => `Books ${a} to ${b}`,
    salaTitulo: "Before the lights go down",
    sala: [
      { t: "Pick the biggest screen.", d: "Nolan made this film for IMAX. On a small screen, the sea loses half its weight." },
      { t: "Don't expect this guide's order.", d: "The poem starts in the middle and jumps through time. The film may do the same, and now you will know where you are." },
      { t: "Follow the gods.", d: "Every storm has an author. When something goes wrong at sea, ask who is angry and why." },
      { t: "It runs 172 minutes.", d: "Arrive early. This story took twenty years to end; three hours is nothing." },
    ],
    hechoPor: "Made by",
    otraVersion: "Traveling with kids? See the illustrated version",
    otraVersionUrl: "../en.html",
  },
};
